---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# guessthecorrelation

<!-- badges: start -->
<!-- badges: end -->

A [{torch}](https://torch.mlverse.org/) dataset of [Curso-R's Guess The Correlation Dataset](https://www.kaggle.com/c/guess-the-correlation).

## Installation

``` r
remotes::install_github("athospd/guessthecorrelation")
```

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(guessthecorrelation)
library(tidyverse)
```

```{r}
train <- guess_the_correlation_dataset(root = "~/datasets", token = "kaggle.json", download = TRUE, split = "train")
submition <- guess_the_correlation_dataset(root = "~/datasets", token = "kaggle.json", download = TRUE, split = "submition")
```

```{r}
transform <- function(x) {
  x
}

plot_one_img <- function(idx) {
  train[idx]$x %>%
  transform() %>%
  as.array() %>%
    as_tibble() %>%
    rowid_to_column(var = "Y") %>%
    gather(key = "X", value = "value", -Y) %>%
    mutate(X = as.numeric(gsub("V", "", X))) %>%
    ggplot(aes(X, rev(Y), fill = value)) +
    geom_raster() +
    theme_void() +
    theme(legend.position = "none") +
    theme(aspect.ratio = 1) +
    ggtitle(glue::glue("corr: {round(train[idx]$y, 3)}")) +
    scale_fill_gradient(high = "white", low = "black")
}

library(patchwork)
map(1:10, plot_one_img) %>% reduce(`+`) + plot_layout(ncol = 5)
```
